on: [pull_request]

name: Test R scripts

jobs:
  Test-r-scripts:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Install dependencies from CRAN
        run: |
          install.packages("rmarkdown")
          install.packages("knitr")
          install.packages("renv")
          dependencies <- unique(renv::dependencies("PACTA_analysis")$Package)
          base <- c("utils", "base", "tools")
          dev <- c(
            "create_interactive_report",
            "PACTA.analysis",
            "StressTestingModelDev"
          )
          exclude <- c("R", base, dev)
          install.packages(setdiff(dependencies, exclude))
        shell: Rscript {0}
