on: [pull_request]

name: Test R scripts

jobs:
  Test-r-scripts:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Install dependencies from CRAN
        run: |
          deps <- unique(renv::dependencies("../PACTA_analysis")$Package)
          exclude <- c(
            "R",
            "utils",
            "base",
            "tools",
            "create_interactive_report",
            "PACTA.analysis",
            "StressTestingModelDev"
          )
          install.packages(setdiff(deps, exclude))
        shell: Rscript {0}
